name: Triggering Events
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows

on:
  ### https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
    paths:
      - '**.tf'      # Terraform files
      - '**.yaml'    # Kubernetes manifests
      - 'src/**'     # Source code
    paths-ignore:
      - 'docs/**'    # Ignore docs
      - 'README.md'

  # Pull Request: Target specific branches, types, and paths
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
    paths:
      - '**.tf'
      - 'k8s/**'      # Kubernetes configs
    paths-ignore:
      - '*.md'

  ### https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  # schedule:
  #   - cron: "0 0 * * *" # Midnight UTC

  ## Manual Trigger
  workflow_dispatch:
  
jobs:
  echo-event:
    runs-on: ubuntu-24.04
    steps:
      - name: Dump full event JSON
        run: |
          echo "=== $GITHUB_EVENT_NAME payload ==="
          cat "$GITHUB_EVENT_PATH"


    
      - name: Dump full event JSON
        run: |
          echo "=== $GITHUB_EVENT_NAME payload ==="
          cat "$GITHUB_EVENT_PATH"
